ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/spi/mediatek/$(MTK_PLATFORM)/


obj-$(CONFIG_MTK_FINGERPRINT) := focal_fp_sensor.o



